apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-service
  name: nodejs-service
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs-service
  type: ClusterIP
status:
  loadBalancer: {}
